experiment_name: dry_run
ksp: "data/test_sample/corrupted_kspace.npy"
mps: "data/test_sample/cc_maps.npy"
sampling_mask: "data/test_sample/sampling_mask_4_shots.npy"
output_dir: "data/"
parameters:
  level_2_iter: 2
  level_1_iter: 2
slurm:
  account: def-mchiew
  mem_per_cpu: 32G 
  gpus_per_node: v100l:1
  time: "23:00:00"